version: "3.8"

x-defaults: &default
  restart: unless-stopped
  labels:
    project: "feathers-nats"
  env_file:
    - .env

services:
  mongo:
    <<: *default
    container_name: feathers-mongo_${ENVIRONMENT}
    image: mongo:4.2.3-bionic
    networks:
      - private
    volumes:
      - feathers-mongo:/data/db
      - feathers-mongo:/data/configdb
    ports:
      - "${HOST_IP}:27017:27017"

  nats:
    <<: *default
    container_name: feathers-nats_${ENVIRONMENT}
    image: nats:2.1.7-linux
    networks:
      - private
    ports:
      - "${HOST_IP}:4222:4222"
      - "${HOST_IP}:6222:6222"
      - "${HOST_IP}:8222:8222"

  test:
    <<: *default
    container_name: feathers-test_${ENVIRONMENT}
    build: .
    networks:
      - private
    depends_on:
      - nats
    #command: npm run start:${ENVIRONMENT}
    volumes:
      - test-node_modules:/app/node_modules
      - ./:/app

    command: tail -f /dev/null

networks:
  private:
    name: feathers-mq_${ENVIRONMENT}
    driver: bridge
    ipam:
      driver: default

volumes:
  test-node_modules:
  feathers-mongo:
